version: "3.6"

services:
  kong:
    image: kong-nokia:latest
    # 0.14.1
    container_name: kong
    depends_on:
      - postgres
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
      - 8003:8003
      - 9443:8443
      - 8444:8444
#    command: "kong start --run-migrations " #
    environment:
      - KONG_ENFORCE_RBAC=on
      - KONG_RBAC_INITIAL_ADMIN_PASS=foo
#      - KONG_LOG_LEVEL=debug
      - KONG_PORTAL=on
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
#      - KONG_PORTAL_API_URI=0.0.0.0:8000/portal
      - KONG_PORTAL_GUI_URI=localhost:8003
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
#      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
#      - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
#      - KONG_VITALS=on
#      - KONG_ANONYMOUS_REPORTS=off
    volumes:
      - ./etc/kong:/etc/kong
      - ./ssl:/usr/local/kong/ssl
  

