_format_version: "1.1"

services:
- name: my-service
  url: http://localhost:7000
  plugins:
  - name: key-auth
  routes:
  - name: my-route
    paths:
    - /

consumers:
- username: my-user
  keyauth_credentials:
  - key: my-key

